### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by asman1337** [jakubdybczak/budgetto#3]
I created firebase app and turned on Google Login and created database also.
But Still whenever I am trying to login it's saying "Sign-in failed"

**Comment by Yacubane** [comment]
Have you tried checking logs in adb?

**Comment by azizsan** [comment]
I receive the same error and I sent you an email. Can you check

**Comment by Yacubane** [comment]
> I receive the same error and I sent you an email. Can you check

Hi. I didn't got any mail. Did you send to jakub.dybczak@gmail.com ?

**Comment by Yacubane** [comment]
It seems that problem was with Firebase / google-services.json configuration. I had a conversation with @azizsan and decided to make visual tutorial on how to build & run this project. It's now in README.MD.
